### ISSUE TITLE
Beacon ready?

### ISSUE THREAD

**Issue by nkirsch** [jeffreyfultonca/Beacon#1]
I used this great tutorial to build a simple iOS app for detecting iBeacons: https://www.raywenderlich.com/152330/ibeacon-tutorial-ios-swift

I'm then able to see an iBeacon I setup on a Linux machine, using this:
https://github.com/dburr/linux-ibeacon

This works successfully. However, I cannot seem to find anything advertised by Beacon.

How do you verify Beacon is working?

I'm on Sierra (10.12.14) and a MacBook Pro (Retina, 13-inch, Early 2015).

Thanks!

**Comment by jeffreyfultonca** [comment]
Hello @nkirsch!

Thanks for trying this out and asking this question. Pardon the late reply, I don't think I had GitHub notifications setup correctly and did not see this until today.

I'm running Sierra (10.12.6) on a MacBook Pro (Retina, 15-inch, Late 2013).

I've confirmed Beacon is successfully broadcasting on my machine but I had to play with the advertised power value in order to see any results with the Ray Wenderlich tutorial app you referenced. I found that setting a power level of `-59` worked well.

The first debugging step I tried was to add breakpoints and print() statements to the tutorial app in `ItemsViewController.locationManager(_: didRangeBeacons: in:)`. This showed the app was in fact detecting the signal from Beacon but the `proximity` and `rssi` values were 0. I started playing around with the advertising power value in Beacon and found that `-59` resulted in reasonable `proximity` and `rssi` values showing up in the tutorial app.

I also pushed a small update to Beacon which sets sensible defaults for all broadcast values, including a power level of `-59`. Please pull the latest and try setting a power level of `-59`.

Good luck and let me know how it goes!
